#!/bin/bash
#
# actions lifecycle: stop, build, deploy, start
#
# The application will work only if it binds to:
# - ip address: $OPENSHIFT_DIY_IP
# - port:       $OPENSHIFT_DIY_PORT

set -x

if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_102 ]; then
    cd $OPENSHIFT_DATA_DIR
     wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.tar.gz
    tar xvf *.tar.gz
    rm -f *.tar.gz
fi

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_102
export PATH=$JAVA_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR
#bash gradlew -g /tmp build -x text
bash build/libs/*.jar &

sleep 30 # wait a little for spring bootstrapping...
