#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
set -x

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_102
export PATH=$JAVA_HOME/bin
#export PATH=$JAVA_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR
java -jar build/libs/*.jar &
# exec build/libs/openshift-0.0.1.jar &
# ./build/libs/openshift-0.0.1.jar &
# ./build/libs/*.jar &
